# Generated by Django 3.2.6 on 2022-01-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('registrationnumber', models.BigIntegerField()),
                ('branch', models.CharField(choices=[('cse', 'CSE'), ('csit', 'CSIT'), ('ee', 'EE'), ('eee', 'EEE'), ('ece', 'ECE'), ('me', 'ME'), ('ce', 'CE'), ('other', 'OTHER')], default='green', max_length=8)),
                ('year', models.CharField(choices=[('1', '1st'), ('2', '2nd'), ('3', '3rd'), ('4', '4th')], default='green', max_length=4)),
                ('contactnumber', models.BigIntegerField()),
            ],
        ),
    ]
